### PR TITLE
Do not pass --parallel option to old cmake

### LINKED ISSUE #131: 0.1.46 does not work
trying to build snmalloc-rs crate and getting `Unknown argument --parallel` error. works fine with 0.1.45

### LINKED ISSUE #143: Unsupported --parallel flag issued
I'm trying to build a Lambda function in Rust to write to Kafka using the `rdkafka` crate as follows:

```toml
[dependencies]
rdkafka = { version = "0.28.0", features = ["ssl-vendored", "gssapi-vendored", "libz-static", "cmake-build"] }
```

I'm building it using Docker image `ekidd/rust-musl-builder:1.57.0` with apt-get package `libsasl2-dev` installed before running `cargo build --release --target x86_64-unknown-linux-musl`.

Unfortunately when this crate gets build it adds a `--parallel` flag that's not supported by the `cmake` version in that Docker image. Is there any way to disable this flag or autodetect that it's not supported?

See https://github.com/emk/rust-musl-builder/issues/138 for the issue with more detail on the error.

### PR DESCRIPTION
**Pull request by taiki-e**
This parses the cmake version and avoids passing --parallel option to old cmake.

Fixes #131
Fixes #143 

(I confirmed this fix works in a project where I actually ran into issue 131: https://github.com/openrr/openrr/pull/584)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ok, sorry but I've [decided](https://github.com/alexcrichton/cmake-rs/issues/127#issuecomment-1055547244) that I will no longer maintain this crate and it needs a new maintainer.

**Comment by alexcrichton** [comment]
Ok, sorry but I've [decided](https://github.com/alexcrichton/cmake-rs/issues/127#issuecomment-1055547244) that I will no longer maintain this crate and it needs a new maintainer.

File: src/lib.rs [hunk 1]
```diff
@@ -928,6 +934,53 @@ impl Config {
...
+    fn parse(s: &str) -> Option<Self> {
+        // As of 3.22, the format of the version output is "cmake version <major>.<minor>.<patch>".
+        // ```
+        // $ cmake --version
+        // cmake version 3.22.2
+        //
+        // CMake suite maintained and supported by Kitware (kitware.com/cmake).
+        // ```
+        let version = s.lines().find(|s| s.starts_with("cmake version "))?;
+        let version = &version["cmake version ".len()..]; // strip prefix
```
Comment (m-ou-se) [inline src/lib.rs:957]: If we can assume it's always on the first line, you can simplify this to:
```suggestion
        let version = s.lines().next()?.strip_prefix("cmake version ")?
```

Comment (taiki-e) [reply src/lib.rs:957]: Package managers tend to add extra strings to the version output, so I've adopted a redundant one, but the version output of binaries installed in Ubuntu (apt), macOS (homebrew), and Windows (scoop) were all the same, so I think it is safe to simplify.

As for strip_prefix, I used a method that is compatible with older compilers because I didn't know the MSRV of this crate, but given that master is the 2021 edition that requires the newer rustc, it seems I no longer need to care about that.

**Comment by acshi** [comment]
Could we please get a new release with this fix included? Unfortunately, I just spent several hours on a goose chase with wondering why the cmake version check wasn't working because I thought this code was present in the most recent release when it actually wasn't!
