### PR TITLE
Disable broken Make jobserver support on OSX to fix parallel builds

### LINKED ISSUE #177: jobserver doesn't always work
When using cmake-rs to build a native library, I can see some errors on some platform:
```
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

The problem may be related to https://github.com/alexcrichton/jobserver-rs/issues/47.

This is not an issue with cmake-rs, but cmake-rs can let user to disable jobserver explicitly to get around the problem.

And [tikv/grpc-rs#](https://github.com/tikv/grpc-rs/issues/578#issuecomment-1436777349) also provides a workaround by setting environment variable `CMAKE_BUILD_PARALLEL_LEVEL`. And using generator other than make can also get around the problem (setting environment variable `MAKE_GENERATOR=Ninja` for example).

### PR DESCRIPTION
**Pull request by kesyog**
On OSX, CMake spawns child processes via libuv, which uses the Apple-specific `posix_spawn` attribute
`POSIX_SPAWN_CLOEXEC_DEFAULT`. This attribute blocks child processes, including make, from inheriting all non-stdio file descriptors from the parent process, including those of the Cargo jobserver.

Because make is passed jobserver information via MAKEFLAGS but is unable to access the jobserver, it prints the error shown below and proceeds to run a single-threaded build:

```
make: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

As a workaround, disable jobserver support on OSX so that cmake-rs instead passes `--parallel $NUM_JOBS` to CMake, allowing for a faster, multi-threaded build.

Fixes #177

### CODE REVIEW

**Comment by NobodyXu** [comment]
Note that newer jobserver protocol supports fifo, which passes a path to the filesystem instead of fds.

Jobserver already supports this but I believe it's not the default.

**Comment by kesyog** [comment]
> Note that newer jobserver protocol supports fifo, which passes a path to the filesystem instead of fds.
> 
> Jobserver already supports this but I believe it's not the default.

Yes, but as you noted in https://github.com/rust-lang/cargo/issues/13483#issuecomment-2002361941, this is unlikely to change in Cargo for backwards compatibility reasons. The named pipe jobserver isn’t supported by older versions of make.

An alternate approach I considered is to call make directly rather than `cmake --build` (for make builds only) so that the jobserver fd’s are forwarded correctly. However, using `cmake --build` is more portable, and it’d be a breaking change that would make `build_arg` awkward to define and use.

**Comment by NobodyXu** [comment]
I think it's possible for cargo to inherit jobserver?

I.e. a newer version of make creates a fifo and passes it to cargo, cargo passes it to build-script

**Comment by kesyog** [comment]
Based on https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/build_runner/mod.rs#L93-L110, I think you're right. Cargo will first try to inherit a jobserver if available and will otherwise create a file descriptor-based jobserver. While the default version of make on macOS Sequoia predates FIFO-based jobservers, one could theoretically have installed a newer version of make _and_ be using a nested Cargo instance within a make job. 

While this feels like a niche use case, we could handle this without much effort or complexity by allowing jobserver usage on OSX if and only if `CARGO_MAKEFLAGS` indicates we are using the FIFO-based jobserver protocol. Let me take a stab at that.

**Comment by kesyog** [comment]
I updated the commit to add an exception that allows the jobserver on macOS iff the jobserver is based on a named pipe/fifo

File: src/lib.rs [hunk 1]
```diff
@@ -1115,8 +1121,20 @@ fn fail(s: &str) -> ! {
...
 
+/// Returns whether the given MAKEFLAGS indicate that there is an available
+/// jobserver that uses a named pipe (fifo)
+fn uses_named_pipe_jobserver(makeflags: &OsStr) -> bool {
+    makeflags
+        .to_str()
+        // auth option as defined in
+        // https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html#POSIX-Jobserver
+        .map(|flags| flags.contains("--jobserver-auth=fifo:"))
+        .unwrap_or(false)
```
Comment (NobodyXu) [inline src/lib.rs:1132]: IMO `to_string_lossy` is better here, since the path could contain non utf-8 characters

```suggestion
    makeflags
        .to_string_lossy()
        // auth option as defined in
        // https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html#POSIX-Jobserver
        .contains("--jobserver-auth=fifo:")
```

**Review by NobodyXu — CHANGES_REQUESTED** [review]
Thanks for adopting my advice!

Not a maintainer but I have another nit suggestion regarding fifo checking:

**Review by NobodyXu — APPROVED** [review]
Thanks for taking my advice!

I'm not a maintainer so you would need to get someone else to review & merge it

**Comment by kesyog** [comment]
Thanks for the review @NobodyXu

@tgross35 any chance you could help get this merged and tag a new crate version?

**Comment by kesyog** [comment]
> @tgross35 any chance you could help get this merged and tag a new crate version?

Or perhaps @thomcc based on https://github.com/rust-lang/cmake-rs/issues/127#issuecomment-1294382049 and https://www.rust-lang.org/governance/teams/library? Hopefully not being too spammy here.

**Comment by tgross35** [comment]
Thom knows this crate better so probably a better reviewer, but I can merge this if we don't hear back in a few days.

**Comment by kesyog** [comment]
@tgross35 mind taking another look?

File: src/lib.rs [hunk 2]
```diff
@@ -837,16 +837,22 @@ impl Config {
...
+                //   However, if the jobserver is based on a named pipe, this will be available to
+                //   the build.
                 Some(ref makeflags)
                     if !(cfg!(windows)
                         || cfg!(target_os = "openbsd")
                         || cfg!(target_os = "netbsd")
                         || cfg!(target_os = "freebsd")
-                        || cfg!(target_os = "dragonfly")) =>
+                        || cfg!(target_os = "dragonfly")
+                        || (cfg!(target_os = "macos")
```
Comment (tgross35) [inline src/lib.rs:854]: Does this apply to other Apple platforms? If so, `target_family = "apple"` may be more applicable.

**Review by tgross35 — COMMENTED** [review]
One question but this seems reasonable to me. @madsmtm you may want to take a look as well, since it touches builds on Apple platforms.

File: src/lib.rs (hunk 2 above)
Comment (kesyog) [reply src/lib.rs:854]: I'm open to whichever option you prefer. The CMake/libuv fd-closing behavior is gated on `defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED >= 1080`. See https://github.com/Kitware/CMake/blob/master/Utilities/cmlibuv/src/unix/process.c#L39-L44 for reference.

Comment (madsmtm) [reply src/lib.rs:854]: Just go with `target_os = "macos"`, that's clearer here

Comment (kesyog) [reply src/lib.rs:854]: sounds good thanks

**Review by tgross35 — APPROVED** [review]

**Comment by tgross35** [comment]
The `linker_messages` failure stopped CI, have to wait for the next nightly to release.

**Comment by tgross35** [comment]
Released in 0.1.53 https://github.com/rust-lang/cmake-rs/pull/233
